modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="GNU General Public License v3.0"
issueTrackerURL="https://github.com/PumpkinBear111/bigredbutton/issues" #optional
[[mods]] #mandatory
modId="bigredbutton" #mandatory
version="1.16.4-1.0.0" #mandatory
displayName="Big Red Button Mod" #mandatory
#updateJSONURL="http://myurl.me/" #optional
displayURL="https://github.com/PumpkinBear111/bigredbutton/wiki" #optional
logoFile="bigredbuttonlogo.png" #optional
credits="TurtyWurty for his modding tutorials, and Minecraft" #optional
authors="PumpkinBear111" #optional
description='''
A mod that adds in 4 buttons to the game that do different types of explosions.
'''