modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="To Be Determined"
#issueTrackerURL="http://my.issue.tracker/" #optional
[[mods]] #mandatory
modId="bigredbutton" #mandatory
version="1.0.0" #mandatory
displayName="BigRedButton" #mandatory
#updateJSONURL="http://myurl.me/" #optional
#displayURL="http://example.com/" #optional
#logoFile="bigredbutton.png" #optional
credits="TurtyWurty for his modding tutorials, and Minecraft" #optional
authors="PumpkinBear111" #optional
description='''

'''